PLANBTI/PLANBTI

src/main/resources/static/resource/common/common.css, src/main/resources/templates/common/layout.html
모든 화면의 기본이 되는 레이아웃 파일을 작성했습니다.
navbar와 footer가 포함되어 있습니다.
=> design: 기본 레이아웃 파일 작성

src/main/java/com/example/demo/boundedContext/member/controller/MemberController.java, src/main/resources/templates/member/modify.html, src/main/resources/templates/member/myPage.html, src/main/resources/templates/member/orderlist.html
=> feat: MyPage 관련 html 파일 작성

src/main/java/com/example/demo/base/entity/BaseEntity.java, src/main/java/com/example/demo/boundedContext/category/entity/Category.java, src/main/java/com/example/demo/boundedContext/faq/entity/Comment.java, src/main/java/com/example/demo/boundedContext/faq/entity/Faq.java, src/main/java/com/example/demo/boundedContext/member/entity/Address.java, src/main/java/com/example/demo/boundedContext/member/entity/Member.java, src/main/java/com/example/demo/boundedContext/member/entity/Test.java, src/main/java/com/example/demo/boundedContext/order/entity/Order.java, src/main/java/com/example/demo/boundedContext/order/entity/OrderDetail.java, src/main/java/com/example/demo/boundedContext/product/entity/Product.java, src/main/java/com/example/demo/boundedContext/product/entity/Review.java, src/main/java/com/example/demo/boundedContext/product/entity/ShoppingBasket.java, src/main/java/com/example/demo/boundedContext/product/entity/WishList.java
BaseEntity에 id, deleteDate 추가하고 모든 엔티티가 상속받도록 했습니다.
=> fix: BaseEntity 수정 후 모든 엔티티에 적용

build.gradle, src/main/java/com/example/demo/base/AppEnv.java, src/main/java/com/example/demo/base/Config.java, src/main/java/com/example/demo/base/exception/OrderException.java, src/main/java/com/example/demo/base/initdata/CustomInitData.java, src/main/java/com/example/demo/boundedContext/member/controller/MemberController.java, src/main/java/com/example/demo/boundedContext/member/entity/Member.java, src/main/java/com/example/demo/boundedContext/order/controller/OrderController.java, src/main/java/com/example/demo/boundedContext/order/controller/TossController.java, src/main/java/com/example/demo/boundedContext/order/dto/OrderRequest.java, src/main/java/com/example/demo/boundedContext/order/entity/Order.java, src/main/java/com/example/demo/boundedContext/order/entity/OrderDetail.java, src/main/java/com/example/demo/boundedContext/order/entity/OrderStatus.java, src/main/java/com/example/demo/boundedContext/order/repository/OrderRepository.java, src/main/java/com/example/demo/boundedContext/order/service/OrderService.java, src/main/resources/application-test.yml, src/main/resources/application.yml, src/main/resources/static/js/order.js, src/main/resources/templates/error/4xx.html, src/main/resources/templates/error/5xx.html, src/main/resources/templates/member/login.html, src/main/resources/templates/order/orderPage.html, src/test/java/com/example/demo/boundedContext/order/controller/OrderControllerTest.java, src/test/java/com/example/demo/boundedContext/order/repository/OrderRepositoryTest.java
1. 기존의 커밋이 포함되어 있어서 앞 부분은 안 보셔도 될 것 같습니다.
2. 정산 로직의 경우 다른 테이블과의 연동이 필요하여 아주 기본적인 부분만 구현하였습니다.
3. **html**의 경우 `null`값이 들어가면 에러가 나기 때문에 만약 에러가 난다면 `null`값을 먼저 체크해주세요
4. **initData**의 경우 알 맞게 값을 변경하여 사용하시면 됩니다.
5. 실행 시 `ddl error`가 난다면 **create -> update**로 바꿔서 돌리고 난 후 다시 **create**로 하면 해결이 됩니다.
6. **toss key**에는 자신의 키를 넣어주세요 (`secret.yml`에 넣어서 사용하기)
=> toss payment 및 다른 부가 기능들 추가 구현

src/main/java/com/example/demo/boundedContext/member/dto/MemberDto.java, src/main/java/com/example/demo/boundedContext/order/controller/OrderController.java, src/main/java/com/example/demo/boundedContext/order/controller/TossController.java, src/main/java/com/example/demo/boundedContext/order/entity/Order.java, src/main/java/com/example/demo/boundedContext/order/repository/OrderDetailRepository.java, src/main/java/com/example/demo/boundedContext/order/service/OrderService.java, src/main/java/com/example/demo/boundedContext/product/repository/ProductRepository.java, src/main/java/com/example/demo/util/rq/ResponseData.java, src/main/java/com/example/demo/util/rq/Rq.java, src/main/resources/application.yml, src/main/resources/static/js/order.js, src/test/java/com/example/demo/boundedContext/order/controller/OrderControllerTest.java, src/test/java/com/example/demo/boundedContext/order/repository/OrderRepositoryTest.java, src/test/java/com/example/demo/boundedContext/order/service/OrderServiceTest.java
주문 검증 로직 백엔드부분입니다.
1. 주문 검증 로직 구현 및 테스트 코드 작성
2. **rq**클래스 도입
**[주의]**
1. **front** 작업은 아직 구현이 안 된 상태입니다.
2. **rq클래스**에서 **member entity**를 반환하는 것이 아닌 **dto**로 반환하고 있습니다. 필요한 경우 **dto**의 **id**를 통해서 **member**를 가져와야 합니다.
=> 주문 검증 로직 (백엔드)

src/main/java/com/example/demo/base/map/MapController.java, src/main/java/com/example/demo/boundedContext/member/controller/AddressController.java, src/main/java/com/example/demo/boundedContext/member/controller/MemberController.java, src/main/java/com/example/demo/boundedContext/member/entity/Address.java, src/main/java/com/example/demo/boundedContext/member/entity/Member.java, src/main/java/com/example/demo/boundedContext/member/repository/MemberRepository.java, src/main/java/com/example/demo/boundedContext/member/service/AddressService.java, src/main/java/com/example/demo/boundedContext/member/service/MemberService.java, src/main/resources/templates/common/layout.html, src/main/resources/templates/map/map.html
페이지에 접속하면 바로 꽃집들을 보여줄 수 있는 API는 카카오 API밖에 없는 것 같아 일단 카카오 API를 적용했습니다.
네이버나 구글 API를 사용하려면 크롤링을 이용해야 할 것 같은데, 좀 더 알아보고 수정하려고 합니다.
=> feat & refactor: 지도 페이지 제작 및 Member 관련 코드 리팩토링

build.gradle, src/main/java/com/example/demo/base/event/EventAfterCreateAddress.java, src/main/java/com/example/demo/base/event/EventAfterDeleteAddress.java, src/main/java/com/example/demo/base/event/EventAfterModifyAddress.java, src/main/java/com/example/demo/base/event/MemberEventListener.java, src/main/java/com/example/demo/base/initdata/CustomInitData.java, src/main/java/com/example/demo/boundedContext/member/controller/AddressController.java, src/main/java/com/example/demo/boundedContext/member/entity/Address.java, src/main/java/com/example/demo/boundedContext/member/repository/AddressRepository.java, src/main/java/com/example/demo/boundedContext/member/service/AddressService.java, src/main/java/com/example/demo/boundedContext/member/service/MemberService.java, src/main/resources/application-secret.default, src/main/resources/schema.sql, src/main/resources/templates/address/create.html, src/main/resources/templates/address/modify.html, src/main/resources/templates/member/profile.html, src/test/java/com/example/demo/boundedContext/member/controller/AddressControllerTest.java, src/test/java/com/example/demo/boundedContext/member/controller/MemberControllerTest.java, src/test/java/com/example/demo/boundedContext/member/service/MemberServiceTest.java
제목과 같이 테스트 코드를 작성했습니다.
레디스 의존성을 추가하고 application-secret.default 파일에 내용을 추가했습니다.
AddressController 중에서 delete 메서드에서 오류가 나서 주석 처리해서 PR 올리니 참고 부탁드립니다!
=> feat: AddressController, MemberService 테스트

src/main/resources/templates/address/create.html, src/main/resources/templates/address/modify.html, src/main/resources/templates/adm/admLayout.html, src/main/resources/templates/adm/faqList.html, src/main/resources/templates/adm/main.html, src/main/resources/templates/adm/members.html, src/main/resources/templates/adm/reviews.html, src/main/resources/templates/common/layout.html, src/main/resources/templates/faq/create.html, src/main/resources/templates/faq/faq.html, src/main/resources/templates/faq/modify.html, src/main/resources/templates/member/faqList.html, src/main/resources/templates/member/myPage.html, src/main/resources/templates/member/orderlist.html, src/main/resources/templates/member/profile.html, src/main/resources/templates/member/shoppingbasket.html, src/main/resources/templates/member/testResult.html
common/layout과 adm/admLayout을 수정하였습니다.
기본 레이아웃이 변경된 거라 다른 페이지들도 다 조금씩 변경이 필요합니다. 이해 부탁드립니다!
건의 하나 하자면 페이지에 들어갈 내용만 다 정리가 되면 제가 마지막에 html 파일 전체를 정리하는 것도 괜찮을 것 같습니다. 일관성을 위해서도요! 고려해주시면 감사하겠습니다
=> design : 기본 레이아웃 수정

src/main/java/com/example/demo/base/config/RedisConfig.java, src/main/java/com/example/demo/base/config/RedisProdConfig.java, src/main/java/com/example/demo/base/event/listen/BaseEventListener.java, src/main/java/com/example/demo/base/redis/RedisInfo.java, src/main/java/com/example/demo/base/security/config/SecurityConfig.java, src/main/java/com/example/demo/boundedContext/member/controller/MemberController.java, src/main/java/com/example/demo/boundedContext/member/dto/MemberChangeDto.java, src/main/java/com/example/demo/boundedContext/order/controller/OrderController.java, src/main/java/com/example/demo/boundedContext/order/entity/Order.java, src/main/java/com/example/demo/boundedContext/order/repository/CustomOrderRepository.java, src/main/java/com/example/demo/boundedContext/order/repository/CustomOrderRepositoryImpl.java, src/main/java/com/example/demo/boundedContext/order/repository/OrderRepository.java, src/main/java/com/example/demo/boundedContext/order/service/OrderService.java, src/main/java/com/example/demo/boundedContext/order/service/ProductFacade.java, src/main/java/com/example/demo/boundedContext/product/controller/ProductController.java, src/main/java/com/example/demo/boundedContext/product/service/ProductService.java, src/main/resources/templates/member/orderlist.html, src/main/resources/templates/product/detail.html, src/test/java/com/example/demo/boundedContext/order/service/ProductFacadeTest.java
=> order detail 페이지 연동

Dockerfile, build.gradle, src/main/java/com/example/demo/base/config/RedisConfig.java, src/main/java/com/example/demo/base/config/RedisProdConfig.java, src/main/java/com/example/demo/base/initdata/CustomInitData.java, src/main/resources/application-prod.yml, src/main/resources/application.yml
> #### Dockerfile 추가 / 수정
- prod 환경이 부족해서 dev로 진행 후에 prod로 전환
> #### prod 환경 세팅
> Gradle
- DB 드라이버 주석 제거
> RedisCofig, RedisProdConfig
- RedisCofig: @Profile("prod") 추가
- RedisProdConfig: @Profile("ex")로 변경
- CustomInitData: @Profile("prod") 추가
> yml 파일
- application-prod.yml
- datasource 정보 추가
- redis 설정 추가
- ddl-auto 수정
- baseUrl
- application.yml
- redirect-uri 수정
- baseUrl
----
초반에 테스트 형식으로 진행한 것이 있어서 마지막 3개가 진짜 커밋입니다..!
=> docs & refactor: 배포

src/main/java/com/example/demo/base/config/SwaggerConfig.java, src/main/java/com/example/demo/base/security/config/SecurityConfig.java, src/main/java/com/example/demo/base/security/filter/PrometheusAuthenticationFilter.java, src/main/java/com/example/demo/boundedContext/faq/Controller/CommentController.java, src/main/java/com/example/demo/boundedContext/faq/Controller/FaqController.java, src/main/java/com/example/demo/boundedContext/member/controller/AddressController.java, src/main/java/com/example/demo/boundedContext/member/controller/MbtiTestController.java, src/main/java/com/example/demo/boundedContext/member/controller/MemberController.java, src/main/java/com/example/demo/boundedContext/order/controller/OrderController.java, src/main/java/com/example/demo/boundedContext/order/controller/TossController.java, src/main/java/com/example/demo/boundedContext/product/controller/ProductController.java, src/main/java/com/example/demo/boundedContext/product/controller/ShoppingBasketController.java, src/main/resources/application.yml
=> Swagger, filter

src/main/java/com/example/demo/boundedContext/product/entity/Basket.java, src/main/java/com/example/demo/boundedContext/product/service/ShoppingBasketService.java
=> fix: 장바구니 기능 로직 오류 수정

src/main/java/com/example/demo/boundedContext/member/controller/MbtiTestController.java, src/main/java/com/example/demo/boundedContext/member/entity/MbtiTest.java, src/main/java/com/example/demo/boundedContext/member/service/TestService.java, src/main/resources/templates/member/mbtiTest.html, src/main/resources/templates/member/testResult.html
> 이미지URL 추가
- MbtiTest 엔티티
- testService
- mbtiTest.html
- testResult.html
> "서비스 더 이용하기" 오류
- mbtiTest.html 내부 자바스크립트로 처리
=> feat & refactor: 테스트 결과 페이지 이미지URL 추가 및 일부 수정

src/main/resources/templates/order/orderPage.html
=> refactor: 토스 url 변경

src/main/java/com/example/demo/base/initdata/CustomInitData.java, src/main/resources/templates/member/mbtiTest.html, src/main/resources/templates/order/exchange.html, src/main/resources/templates/order/orderPage.html, src/main/resources/templates/product/detail.html, src/main/resources/templates/shop/shopMain.html
카테고리 별로 상품을 15개씩 생성하였습니다. 어느 카테고리든 내용은 같습니다.
html도 일부 수정했는데 주문 결과와 교환 요청 페이지는 못 했습니다. 참고 부탁드립니다.
=> 초기화 데이터 생성 및 html 수정

src/main/resources/templates/adm/productModify.html, src/main/resources/templates/adm/productRegister.html, src/main/resources/templates/adm/reviews.html, src/main/resources/templates/adm/sales.html, src/main/resources/templates/member/orderlist.html
=> design: html 수정

src/main/java/com/example/demo/base/shop/ShopController.java, src/main/java/com/example/demo/base/shop/ShopService.java, src/main/java/com/example/demo/boundedContext/product/repository/product/ProductQueryDslRepository.java, src/main/java/com/example/demo/boundedContext/product/repository/product/ProductQueryDslRepositoryImpl.java, src/main/resources/templates/about/about.html, src/main/resources/templates/shop/shopMainAll.html
카테고리를 파라미터로 받아서 처리하려고 했는데 페이징 처리하는 부분 때문에 로직이 복잡해져서 일단 '/shop', '/shop/카테고리' 이렇게 따로 만들었으니 참고 부탁드립니다! 내일 시간되는 대로 /shop 페이지 하나로만 이용 가능하게 변경할 생각입니다.
=> feat : About, Main 페이지

src/main/java/com/example/demo/boundedContext/member/controller/MbtiTestController.java, src/main/resources/application.yml, src/main/resources/templates/member/mbtiTest.html
> MbtiTestController 수정
> mbtiTest.html 응답 수정
=> refactor & docs: 테스트 결과 응답 수정

src/main/java/com/example/demo/base/adm/controller/AdmController.java, src/main/java/com/example/demo/boundedContext/product/dto/ProductRegisterDto.java, src/main/java/com/example/demo/boundedContext/product/service/ProductService.java
- 상품 등록 시 null 값이 들오면 rq로 반환하도록 하였습니다
=> refactor : 상품 등록 리펙토링

src/main/resources/templates/member/mbtiTest.html, src/main/resources/templates/product/detail.html, src/test/java/com/example/demo/boundedContext/product/controller/ProductControllerTest.java
> ProductControllerTest 오류 
> 일부 html 수정
- detail.html 일부 수정
- mbtiTest.html "닫기" 버튼 수정
=> refactor & design: ProductControllerTest 오류 해결 및 일부 html 수정

src/main/java/com/example/demo/base/shop/ShopController.java, src/main/java/com/example/demo/base/shop/ShopService.java, src/main/java/com/example/demo/boundedContext/product/repository/product/ProductQueryDslRepositoryImpl.java, src/main/java/com/example/demo/boundedContext/product/repository/product/ProductRepository.java, src/main/java/com/example/demo/boundedContext/product/service/ProductService.java
=> fix :  삭제 후 목록 조회 되는 오류 수정

src/main/resources/templates/map/map.html, src/main/resources/templates/product/detail.html
리뷰에 평점이 보이게 했는데 더보기를 클릭해서 나온 리뷰에는 보이지 않아 삭제했습니다.
=> design: html 잘못된 부분 수정

src/main/resources/templates/member/mbtiTest.html, src/main/resources/templates/member/testResult.html
=> design: mbtiTest.html 수정

src/main/java/com/example/demo/boundedContext/member/service/TestService.java, src/main/resources/templates/member/mbtiTest.html, src/main/resources/templates/member/testResult.html
> 테스트 결과 조회 버그 수정
- 2개 이상 결과 추가 오류 해결
> 테스트 결과 페이지 보완
- 로딩 중앙정렬
- progress 바 추가
- 주석 제거
=> fix & design: 테스트 결과 조회 버그 수정 및 테스트 결과 페이지 보완

src/main/java/com/example/demo/base/adm/controller/AdmController.java, src/main/java/com/example/demo/base/adm/service/AdmOrderDetailService.java, src/main/java/com/example/demo/base/initdata/CustomInitData.java, src/main/java/com/example/demo/boundedContext/member/entity/Member.java, src/main/java/com/example/demo/boundedContext/member/repository/MemberRepository.java, src/main/java/com/example/demo/boundedContext/order/entity/OrderItemStatus.java, src/main/resources/templates/adm/orders.html, src/test/java/com/example/demo/base/adm/controller/AdmControllerTest.java, src/test/java/com/example/demo/base/adm/service/AdmOrderDetailServiceTest.java, src/test/java/com/example/demo/boundedContext/member/service/AddressServiceTest.java
COMPLETED -> 결제 완료, DONE -> 구매 확정으로 변경하였습니다.
변경하면서 실패하게 된 테스트도 수정했습니다.
=> refactor: 결제 완료 상태와 구매 확정 상태 변경
